# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  release:
    types: [created, published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  draft_build:
    runs-on: ubuntu-latest
    if: github.event.release.draft
    steps:
      - uses: actions/checkout@v2

      - name: Run on draft
        run: 'echo "draft: ${{ github.event.release.draft }}"'

  pre-release_build:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease
    steps:
      - uses: actions/checkout@v2

      - name: Run on pre-release
        run: 'echo "pre-release: ${{ github.event.release.prerelease }}"'

  release_build:
    runs-on: ubuntu-latest
    if: "!(github.event.release.draft || github.event.release.prerelease)"
    steps:
      - uses: actions/checkout@v2

      - name: Run on release
        run: 'echo "release: ${{ !(github.event.release.draft || github.event.release.prerelease) }}"'
